# Generated by Django 4.2.29 on 2026-04-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='adimplente',
            field=models.BooleanField(default=True, help_text='Se False, bloqueia acesso do condomínio ao sistema'),
        ),
    ]
