# Generated by Django 4.2.29 on 2026-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_condominio_adimplente'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='blocos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de blocos/torres, ex: ["A","B","C"] ou ["Torre 1","Torre 2"]'),
        ),
    ]
