# Generated by Django 4.2.29 on 2026-04-02 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf_hash', models.CharField(max_length=64, unique=True)),
                ('apartamento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('biometria_hash', models.CharField(blank=True, default='', max_length=64)),
                ('webauthn_credential', models.JSONField(blank=True, null=True)),
                ('cadastro_completo', models.BooleanField(default=False)),
                ('convite_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='condominios.condominio')),
            ],
            options={
                'verbose_name_plural': 'eleitores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='eleitor',
            constraint=models.UniqueConstraint(fields=('condominio', 'apartamento'), name='unique_eleitor_apartamento'),
        ),
    ]
