# Generated by Django 4.2.29 on 2026-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='bloco',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='perfil',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('procurador', 'Procurador')], default='proprietario', max_length=20),
        ),
    ]
