# Generated by Django 4.2.29 on 2026-04-02 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembleias', '0001_initial'),
        ('eleitores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metodo_auth', models.CharField(choices=[('facial', 'Biometria Facial'), ('webauthn', 'WebAuthn'), ('otp', 'OTP')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('hash_voto', models.CharField(max_length=64, unique=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='assembleias.assembleia')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='eleitores.eleitor')),
                ('opcao_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='assembleias.opcaovoto')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='assembleias.questao')),
            ],
            options={
                'verbose_name_plural': 'votos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('eleitor', 'questao'), name='unique_voto_por_questao'),
        ),
    ]
