http:
  routers:
    votacao-api-http:
      entryPoints:
        - http
      rule: "Host(`appvotacao.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`))"
      middlewares:
        - votacao-redirect-https
      service: votacao-backend-svc
      priority: 100

    votacao-api-https:
      entryPoints:
        - https
      rule: "Host(`appvotacao.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`))"
      service: votacao-backend-svc
      tls:
        certResolver: letsencrypt
      priority: 100

    votacao-web-http:
      entryPoints:
        - http
      rule: "Host(`appvotacao.com.br`)"
      middlewares:
        - votacao-redirect-https
      service: votacao-frontend-svc
      priority: 50

    votacao-web-https:
      entryPoints:
        - https
      rule: "Host(`appvotacao.com.br`)"
      service: votacao-frontend-svc
      tls:
        certResolver: letsencrypt
      priority: 50

  middlewares:
    votacao-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    votacao-backend-svc:
      loadBalancer:
        servers:
          - url: "http://votacao-backend:8000"

    votacao-frontend-svc:
      loadBalancer:
        servers:
          - url: "http://votacao-frontend:3000"
