# Generated by Django 4.2.29 on 2026-04-02 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleitores', '0001_initial'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembleia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='rascunho', max_length=20)),
                ('quorum_minimo', models.PositiveIntegerField(default=50, help_text='Percentual mínimo para validade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembleias', to='condominios.condominio')),
                ('votantes', models.ManyToManyField(blank=True, related_name='assembleias', to='eleitores.eleitor')),
            ],
            options={
                'verbose_name_plural': 'assembleias',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='assembleias.assembleia')),
            ],
            options={
                'verbose_name_plural': 'questões',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoVoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='assembleias.questao')),
            ],
            options={
                'verbose_name_plural': 'opções de voto',
                'ordering': ['ordem'],
            },
        ),
    ]
