# Generated by Django 4.2.29 on 2026-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleia',
            name='quorum_segunda_chamada',
            field=models.PositiveIntegerField(default=50, help_text='Percentual mínimo 2ª chamada'),
        ),
        migrations.AddField(
            model_name='assembleia',
            name='segunda_chamada_qualquer_numero',
            field=models.BooleanField(default=False, help_text='Se True, 2ª chamada aceita qualquer número dos presentes'),
        ),
        migrations.AlterField(
            model_name='assembleia',
            name='quorum_minimo',
            field=models.PositiveIntegerField(default=50, help_text='Percentual mínimo 1ª chamada'),
        ),
    ]
