# Generated by Django 4.2.29 on 2026-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0002_assembleia_quorum_segunda_chamada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Documento para download (PDF, orçamento, etc.)', null=True, upload_to='questoes/arquivos/'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do candidato ou imagem ilustrativa', null=True, upload_to='questoes/imagens/'),
        ),
        migrations.AddField(
            model_name='questao',
            name='link_externo',
            field=models.URLField(blank=True, default='', help_text='Link externo (vídeo, documento online, etc.)'),
        ),
    ]
