# Generated by Django 4.2.29 on 2026-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0003_questao_arquivo_questao_imagem_questao_link_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaovoto',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Documento do candidato (PDF, currículo, etc.)', null=True, upload_to='opcoes/arquivos/'),
        ),
        migrations.AddField(
            model_name='opcaovoto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do candidato', null=True, upload_to='opcoes/imagens/'),
        ),
        migrations.AddField(
            model_name='opcaovoto',
            name='link_externo',
            field=models.URLField(blank=True, default='', help_text='Link externo (vídeo, perfil, etc.)'),
        ),
    ]
