# Generated by Django 4.2.29 on 2026-04-02 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0002_eleitor_bloco_eleitor_perfil'),
        ('assembleias', '0004_opcaovoto_arquivo_opcaovoto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('bloco', models.CharField(blank=True, default='', max_length=20)),
                ('apartamento', models.CharField(max_length=20)),
                ('perfil', models.CharField(choices=[('proprietario', 'Proprietário'), ('procurador', 'Procurador')], default='proprietario', max_length=20)),
                ('metodo_auth', models.CharField(default='webauthn', max_length=20)),
                ('horario_entrada', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='assembleias.assembleia')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='eleitores.eleitor')),
            ],
            options={
                'verbose_name_plural': 'presenças',
                'ordering': ['horario_entrada'],
            },
        ),
        migrations.AddConstraint(
            model_name='presenca',
            constraint=models.UniqueConstraint(fields=('assembleia', 'eleitor'), name='unique_presenca_eleitor_assembleia'),
        ),
    ]
