# Generated by Django 4.2.29 on 2026-04-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0005_presenca_presenca_unique_presenca_eleitor_assembleia'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleia',
            name='primeira_chamada_50_mais_1',
            field=models.BooleanField(default=True, help_text='Se True, 1ª chamada exige 50% + 1 (conforme lei)'),
        ),
    ]
