# Generated by Django 4.2.29 on 2026-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleias', '0006_assembleia_primeira_chamada_50_mais_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='assinatura_facial',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 do vetor facial capturado na autenticação', max_length=64),
        ),
    ]
